// Generated by https://quicktype.io

export interface BookingTrip {
    paymentRef: string;
    type: string;
    numberOfTravellers: number;
    bookings: Booking[];
    passengers: Passenger[];
}

export interface Booking {
    price?: number;
    tripId: string;
    seats: string[];
}

export interface Passenger {
    name: string;
    ageBracket: string;
    gender: string;
}
