
export interface Auth {
    accessToken: string;
    refreshToken: string;
    user: User;
}

export interface User {
    id: string;
    firstName: string;
    lastName: string;
    email: string;
    phoneNumber: string;
    verified: boolean;
    profile: Profile;
    gender: 'male' | 'female';
    createdAt: string;
    roles: Role[];
    refreshToken: string;
    updatedAt: string;
}

export interface Role {
    id: string;
    role: string;
}

// Generated by https://quicktype.io

export interface Profile {
    id: string;
    address: string;
    kinFullName: string;
    kinPhoneNumber: string;
    updatedAt: string;
    createdAt: string;
}
